import { Calendar, Clock, ExternalLink, MapPin, Music } from 'lucide-react';
import { ReactNode } from 'react';
import { DanceClass, DanceEvent, MembershipTerms, PhotoItem, RegistrationProcess, VideoItem } from '../types';
import { StructuralImage } from './StructuralImage';

interface Props { section: 'cours' | 'agenda' | 'galerie' | 'conditions'; classes?: DanceClass[]; events?: DanceEvent[]; photos?: PhotoItem[]; videos?: VideoItem[]; registration?: RegistrationProcess; terms?: MembershipTerms; onShowTerms?: () => void; onBack?: () => void; pageTitle?: string; pageSubtitle?: string }
export function LandingContent({ section, classes = [], events = [], photos = [], videos = [], registration, terms, onShowTerms, onBack, pageTitle, pageSubtitle }: Props) {
  if (section === 'cours') return <Page title={pageTitle || "Nos cours"} subtitle={pageSubtitle || "Découvrez les activités proposées par l'association."}>
    <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{classes.filter((item) => item.active !== false).sort((a,b) => (a.order ?? 0) - (b.order ?? 0)).map((item) => <article key={item.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><StructuralImage src={item.image} alt="" className="h-48 w-full object-cover" /><div className="space-y-3 p-6"><h2 className="text-xl font-black">{item.name}</h2><p className="text-sm text-zinc-600 dark:text-zinc-400">{item.description}</p><p className="flex items-center gap-2 text-sm"><Clock size={16} /> {item.schedule}</p><p className="flex items-center gap-2 text-sm"><MapPin size={16} /> {item.location}</p><div className="rounded-2xl bg-lime-50 p-4 dark:bg-lime-950/30"><p className="text-xs font-bold uppercase tracking-wider text-zinc-500">Tarif saison</p><p className="mt-1 text-2xl font-black text-[#557219] dark:text-lime-400">{item.isFree || item.annualPrice === 0 ? 'Gratuit' : `${item.annualPrice} €`}</p></div>{item.helloAssoUrl && <a href={item.helloAssoUrl} target="_blank" rel="noopener noreferrer" className="flex w-full items-center justify-center gap-2 rounded-xl bg-rose-600 px-4 py-3 font-bold text-white hover:bg-rose-700">{item.registrationButtonText || "S’inscrire"} <ExternalLink size={16} /></a>}</div></article>)}</div>
    {registration?.visible && <section className="mx-auto mt-12 max-w-3xl rounded-3xl border border-lime-200 bg-lime-50 p-6 dark:border-lime-900 dark:bg-lime-950/30"><h2 className="text-2xl font-black">{registration.title}</h2><ol className="mt-5 space-y-3">{[...registration.steps].sort((a,b) => a.order-b.order).map((step, index) => <li key={step.id} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#557219] font-bold text-white">{index + 1}</span><span>{step.text}</span></li>)}</ol><p className="mt-5 rounded-xl bg-white/70 p-4 text-sm dark:bg-zinc-900/50">{registration.finalNote}</p></section>}
    {terms?.visible && <div className="mt-8 text-center"><button onClick={onShowTerms} className="font-bold text-rose-600 underline underline-offset-4">Conditions générales d’adhésion</button></div>}
  </Page>;
  if (section === 'agenda') return <Page title={pageTitle || "Agenda"} subtitle={pageSubtitle || "Les rendez-vous, stages et rencontres de La Maloka."}><div className="grid gap-5 md:grid-cols-2">{events.filter((event) => event.active !== false).sort((a,b) => (a.order ?? 0)-(b.order ?? 0)).map((event) => <article key={event.id} className="rounded-3xl border bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><StructuralImage src={event.image} alt="" className="mb-4 h-48 w-full rounded-2xl object-cover" /><Calendar className="mb-4 text-orange-500" /><h2 className="text-xl font-black">{event.title}</h2><p className="mt-2 text-zinc-600 dark:text-zinc-400">{event.description}</p><div className="mt-4 flex flex-wrap gap-4 text-sm"><span>{event.date}</span><span>{event.time}</span><span>{event.location}</span><span>{event.price === 0 ? "Gratuit" : `${event.price} €`}</span></div>{event.externalUrl && <a href={event.externalUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex items-center gap-2 font-bold text-rose-600">En savoir plus <ExternalLink size={15} /></a>}</article>)}</div></Page>;
  if (section === 'conditions') return <Page title={terms?.title ?? 'Conditions générales d’adhésion'} subtitle={`${terms?.subtitle ?? ''} · ${terms?.lastUpdated ?? ''}`}><div className="mx-auto max-w-4xl space-y-5">{terms?.visible ? [...terms.sections].sort((a,b) => a.order-b.order).map((item) => <article key={item.id} className="rounded-2xl border p-5 dark:border-zinc-800"><h2 className="font-black">{item.title}</h2><p className="mt-2 whitespace-pre-line text-sm leading-6 text-zinc-600 dark:text-zinc-300">{item.content}</p></article>) : <p className="text-center">Ces conditions ne sont pas publiées actuellement.</p>}<button onClick={onBack} className="rounded-xl bg-zinc-900 px-5 py-3 font-bold text-white dark:bg-white dark:text-zinc-900">Retour aux cours</button></div></Page>;
  const activePhotos = photos.filter((item) => item.active !== false).sort((a,b) => (a.order ?? 0)-(b.order ?? 0));
  const activeVideos = videos.filter((item) => item.active !== false && /^[A-Za-z0-9_-]{11}$/.test(item.youtubeId ?? '')).sort((a,b) => (a.order ?? 0)-(b.order ?? 0));
  return <Page title={pageTitle || "Photos & Vidéos"} subtitle={pageSubtitle || "Quelques souvenirs de nos cours et événements."}><h2 className="mb-5 text-2xl font-black">Photos</h2>{activePhotos.length ? <div className="columns-1 gap-5 sm:columns-2 lg:columns-3">{activePhotos.map((photo) => <figure key={photo.id} className="mb-5 break-inside-avoid overflow-hidden rounded-3xl bg-zinc-100 dark:bg-zinc-900"><img src={photo.url} alt={photo.title} loading="lazy" className="w-full object-cover" /><figcaption className="p-4"><strong>{photo.title}</strong>{photo.description && <p className="mt-1 text-sm text-zinc-500">{photo.description}</p>}</figcaption></figure>)}</div> : <p className="rounded-xl bg-zinc-100 p-5 dark:bg-zinc-900">Aucune photo publiée.</p>}<h2 className="mb-5 mt-12 text-2xl font-black">Vidéos YouTube</h2>{activeVideos.length ? <div className="grid gap-6 md:grid-cols-2">{activeVideos.map((video) => <article key={video.id} className="overflow-hidden rounded-3xl border dark:border-zinc-800"><div className="aspect-video"><iframe className="h-full w-full" src={`https://www.youtube-nocookie.com/embed/${video.youtubeId}`} title={video.title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div><div className="p-4"><h3 className="font-black">{video.title}</h3>{video.description && <p className="mt-2 text-sm text-zinc-500">{video.description}</p>}</div></article>)}</div> : <p className="rounded-xl bg-zinc-100 p-5 dark:bg-zinc-900">Aucune vidéo publiée.</p>}</Page>;
}
function Page({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <section className="relative mx-auto min-h-[70vh] max-w-7xl px-4 py-16 sm:px-6"><header className="mx-auto mb-12 max-w-2xl text-center"><Music className="mx-auto mb-4 text-rose-500" /><h1 className="text-4xl font-black">{title}</h1><p className="mt-3 text-zinc-600 dark:text-zinc-400">{subtitle}</p></header>{children}</section>; }
